build:
    environment:
        php: '8.2'

    nodes:
        analysis:
            requires:
                - branch: /^master$|^(bugfix|hotfix|beta)\/.+|^feature\/[a-z]+-\d+\/(master|dev)-.+|^feature\/[a-z]+-\d+\/[a-z]+-\d+\/(master|dev)-.+/
            tests:
                override:
                    - php-scrutinizer-run

filter:
    excluded_paths:

build_failure_conditions:
    - 'project.metric("scrutinizer.quality", < 9.88)'
